import { adminClient } from "../_shared/auth.ts";
import { corsHeaders, json } from "../_shared/http.ts";
import { recordAndSendOwnerNotification } from "../_shared/web3forms.ts";

const text=(form:FormData,key:string)=>String(form.get(key)||"").trim();
Deno.serve(async(request)=>{if(request.method==="OPTIONS")return new Response("ok",{headers:corsHeaders});if(request.method!=="POST")return json({error:"Method not allowed"},405);try{
  const form=await request.formData();const productId=text(form,"productId"),fullName=text(form,"fullName"),email=text(form,"email"),whatsapp=text(form,"whatsapp");
  if(!productId||!fullName||!whatsapp)return json({error:"Complete the required customer and product details."},400);
  const db=adminClient();const{data:product}=await db.from("products").select("id,name,price_inr,category_id").eq("id",productId).eq("is_active",true).single();if(!product)return json({error:"This product is unavailable."},404);
  const orderNumber=`MM-${new Date().toISOString().slice(0,10).replaceAll("-","")}-${crypto.randomUUID().slice(0,6).toUpperCase()}`;
  const{data:order,error:orderError}=await db.from("orders").insert({order_number:orderNumber,full_name:fullName,email:email||"not-provided@moonmuse.local",whatsapp,city:text(form,"city")||"To confirm",pin_code:text(form,"pinCode")||"000000",address:text(form,"address")||null,state:text(form,"state")||null,status:"New Request",payment_status:"Pending",handmade_accepted:true,subtotal:product.price_inr,final_total:null,latest_update:"Your personalised request has reached the MoonMuse studio."}).select("id").single();if(orderError||!order)throw new Error("Could not save order");
  await db.from("order_items").insert({order_id:order.id,product_id:product.id,product_name:product.name,creation_mode:"personalised",unit_price:product.price_inr,quantity:1,selected_options:{size:text(form,"size"),variant:text(form,"variant")}});
  await db.from("personalised_order_details").insert({order_id:order.id,occasion:text(form,"occasion")||null,people_count:Number(text(form,"peopleCount"))||null,pets_count:Number(text(form,"petsCount"))||null,names:text(form,"names")||null,important_date:text(form,"importantDate")||null,short_message:text(form,"message")||null,preferred_colours:text(form,"colours")||null,special_details:text(form,"specialDetails")||null,customer_instructions:text(form,"instructions")||null,requested_deadline:text(form,"deadline")||null,selections:{size:text(form,"size"),variant:text(form,"variant")}});
  const files=form.getAll("photos").filter((value):value is File=>value instanceof File&&value.size>0);for(let index=0;index<files.length;index++){const file=files[index];if(!["image/jpeg","image/png","image/webp"].includes(file.type)||file.size>10485760)throw new Error("Invalid customer image");const ext=file.name.split(".").pop()?.toLowerCase()||"jpg";const path=`${order.id}/originals/${crypto.randomUUID()}.${ext}`;const{error:uploadError}=await db.storage.from("custom-orders").upload(path,file,{contentType:file.type});if(uploadError)throw uploadError;await db.from("personalised_order_files").insert({order_id:order.id,file_type:"original",storage_path:path,filename:file.name,mime_type:file.type,byte_size:file.size,display_order:index})}
  await db.from("admin_notifications").insert({kind:"new_order",title:`New personalised order ${orderNumber}`,body:`${fullName} requested ${product.name}.`,related_order_id:order.id});
  const site=(Deno.env.get("PUBLIC_SITE_URL")||"").replace(/\/$/,"");await recordAndSendOwnerNotification(db,{orderId:order.id,recipient:(Deno.env.get("OWNER_NOTIFICATION_EMAIL")||"").trim(),fields:{subject:`New MoonMuse Order ✦ ${orderNumber}`,"Order ID":orderNumber,"Customer name":fullName,"Customer email":email||"Not provided","WhatsApp number":whatsapp,Product:product.name,"Product subtotal":`₹${product.price_inr}`,"Order date":new Date().toISOString(),"Admin order link":`${site}/admin/orders/${order.id}`,message:"A personalised order with private customer photographs has reached MoonMuse."}});
  return json({success:true,orderId:orderNumber,whatsapp},201);
}catch(error){console.error("personalised order failed",{message:error instanceof Error?error.message:"unknown"});return json({error:"The personalised order could not be submitted. Please try again."},500)}});
