import { FormEvent, useEffect, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { PageHero } from "./Layout";
import { money } from "../lib/data";
import { supabase } from "../lib/supabase";

type TrackedOrder = { order_number: string; status: string; latest_update?: string; subtotal: number; delivery_charge?: number; final_total?: number; payment_status?: string; tracking_number?: string; order_items?: Array<{ product_name: string; quantity: number; unit_price: number }> };
export function TrackOrderPage() {
  const [params] = useSearchParams(); const [order, setOrder] = useState<TrackedOrder | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const lookup = async (body: Record<string, string>) => { if (!supabase) return setError("Order tracking is temporarily unavailable."); setBusy(true); setError(""); setOrder(null); const { data, error: invokeError } = await supabase.functions.invoke("track-order", { body }); if (invokeError || !data?.order) setError(data?.error || "We could not verify an order with those details."); else setOrder(data.order); setBusy(false); };
  useEffect(() => { const token = params.get("token"); if (token) void lookup({ token }); }, []);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); void lookup({ orderId: String(data.get("orderId") || ""), identity: String(data.get("identity") || "") }); };
  return <><PageHero eyebrow="Order status" title="Your piece is on its way." text="Enter your details to see where your MoonMuse order is in its journey."/><section className="section !max-w-4xl"><form onSubmit={submit} className="grid gap-4 rounded-3xl bg-white p-6 md:grid-cols-[1fr_1fr_auto]"><input required name="orderId" className="field" placeholder="Order ID, e.g. MM1042"/><input required name="identity" className="field" placeholder="Matching email or WhatsApp number"/><button disabled={busy} className="btn">{busy ? "Checking…" : "Track order"}</button></form>{error && <p role="alert" className="mt-5 rounded-2xl bg-coral/10 p-4 text-coral">{error}</p>}{order && <div className="mt-8 rounded-3xl bg-white p-7"><p className="label">{order.order_number}</p><h2 className="text-4xl">{order.status}</h2><p className="mt-2 text-sm text-ink/60">{order.latest_update || "Your request has reached our studio."}</p><div className="mt-6 space-y-3">{order.order_items?.map((item, index) => <div key={`${item.product_name}-${index}`} className="flex justify-between border-t pt-3"><div><b>{item.product_name}</b><p className="text-xs text-ink/50">Qty {item.quantity}</p></div><b>{money(item.unit_price * item.quantity)}</b></div>)}</div><div className="mt-6 grid gap-3 rounded-2xl bg-cream p-5 sm:grid-cols-2"><p>Subtotal <b className="block">{money(order.subtotal)}</b></p><p>Shipping <b className="block">{order.delivery_charge == null ? "To be confirmed" : money(order.delivery_charge)}</b></p><p>Final total <b className="block">{order.final_total == null ? "To be confirmed" : money(order.final_total)}</b></p><p>Payment <b className="block">{order.payment_status || "Pending"}</b></p>{order.tracking_number && <p>Tracking number <b className="block">{order.tracking_number}</b></p>}</div><a className="btn mt-7" href={`https://wa.me/${import.meta.env.VITE_OWNER_WHATSAPP || ""}`} target="_blank" rel="noreferrer">Message Janvi</a></div>}</section></>;
}
